DROP TABLE IF EXISTS dw.payout;
DROP TABLE IF EXISTS dw.payout_method;
DROP TABLE IF EXISTS dw.payout_tool;
DROP TYPE IF EXISTS dw.payout_account_type;
DROP TYPE IF EXISTS dw.payout_paid_status_details;
DROP TYPE IF EXISTS dw.payout_status;
DROP TYPE IF EXISTS dw.payout_tool_info;
DROP TYPE IF EXISTS dw.payout_type;
ALTER TABLE dw.shop DROP COLUMN payout_tool_id;
ALTER TABLE dw.shop DROP COLUMN payout_schedule_id;